languageCode: en-us
baseURL: http://turitoyuenan.github.io
title: Turito Yuenan

params:
  profilePicture: /favicon.svg
  socialIcons:
    - name: email
      icon: bi-envelope-fill
      url: mailto:turitoyuenan@proton.me
    - name: github
      icon: bi-github
      url: https://github.com/TuritoYuenan
    - name: linkedin
      icon: bi-linkedin
      url: https://linkedin.com/in/TuritoYuenan
    - name: pinterest
      icon: bi-pinterest
      url: https://pinterest.com/TuritoYuenan
    - name: reddit
      icon: bi-reddit
      url: https://reddit.com/u/LeaderTurito
    - name: twitter
      icon: bi-twitter
      url: https://twitter.com/TuritoYuenan
    - name: youtube
      icon: bi-youtube
      url: https://youtube.com/@TuritoYuenan

menu:
  main:
    - identifier: articles
      name: articles
      url: /articles/
      weight: 143
    - identifier: works
      name: works
      url: /works/
      weight: 314
    - identifier: knabino
      name: magical girl's
      url: /magical-girl/
      weight: 667
  frontpage:
    - identifier: certs
      name: Certifications
      url: /certifications/
      weight: 1
    - identifier: coding
      name: Coding Experiences
      url: /coding-experiences/
      weight: 2
    - identifier: music
      name: Music Preferences
      url: /music-preferences/
      weight: 3
