languageCode: en-us
baseURL: http://turitoyuenan.github.io
title: The Internerdt

menu:
  main:
    - name: Contents
      pageRef: /contents
      params:
        symbol: feed
      weight: 1
    - name: Projects
      pageRef: /projects
      params:
        symbol: storage
      weight: 2
    - name: Contact
      pageRef: /contact
      params:
        symbol: language
      weight: 3
    - name: Portfolio
      pageRef: /portfolio
      params:
        symbol: profile
      weight: 4
