languageCode: en-us
baseURL: http://turitoyuenan.github.io
title: Turito Yuenan CMS

menu:
  main:
    - name: Articles
      pageRef: /articles
      params:
        color: var(--ctp-macchiato-red)
      weight: 1
    - name: Projects
      url: https://turitoyuenan.pages.dev/projects
      params:
        color: var(--ctp-macchiato-peach)
      weight: 2
    - name: Connect
      url: https://turitoyuenan.pages.dev/connect
      params:
        color: var(--ctp-macchiato-green)
      weight: 3
    - name: My CV
      pageRef: /cvitae
      params:
        color: var(--ctp-macchiato-blue)
      weight: 4
