languageCode: en-us
baseURL: http://turitoyuenan.github.io
title: Turito Yuenan CMS

params:
  profilePicture: /favicon.svg
  socialIcons:
    - name: email
      icon: bi-envelope-fill
      url: mailto:turitoyuenan@proton.me
    - name: github
      icon: bi-github
      url: https://github.com/TuritoYuenan
    - name: linkedin
      icon: bi-linkedin
      url: https://linkedin.com/in/TuritoYuenan
    - name: pinterest
      icon: bi-pinterest
      url: https://pinterest.com/TuritoYuenan
    - name: reddit
      icon: bi-reddit
      url: https://reddit.com/u/LeaderTurito
    - name: twitter
      icon: bi-twitter
      url: https://twitter.com/TuritoYuenan
    - name: youtube
      icon: bi-youtube
      url: https://youtube.com/@TuritoYuenan
